fix drink counting
kir-dev/BeAlcoholic pull request #47
Opened 2024-08-22 15:47 UTC by murtagh27

2024-08-22 20:06 UTC, Tschonti reviewed
nice work, but we have to think one thing over:
The user is creating drinkActions here, and drinkActions have price and millilitre properties (the drink entity itself contains neither of these infos (currently)). So selecting two beers doesn't make sense right now, instead the user should be able to specify the amount consumed in millilitres. 
Or we could change how we store drinks, and store a defaultVolume with each, then this could work

2024-08-22 20:06 UTC, Tschonti commented on apps/frontend/src/app/events/new/page.tsx
> +  }
you could put this in the return statement

```html
{consumedDrinks.size === 0 ? (
 <li>...</li>
) : (
  Array.from(consumedDrinks.entries()).map(([drink, value]) => ( ... ))
)
```

2024-09-23 19:07 UTC, Tschonti requested changes
I tried running on my machine, and event creation works without problems, as long as you don't send any drinkactions. So maybe it was just a migration error all along.

I think it's best to leave the stuff with the drinkAction dialog for later, we can merge this once the other small issues have been addressed

2024-09-23 19:07 UTC, Tschonti commented on apps/backend/package.json
> +    "zod": "^3.23.8"
all these packages (the ones you added in this PR) are used by the frontend, so these should go to packages/frontend/package.json You can just remove them from this file and move it to the one in the frontend dir, and then execute yarn install

2024-09-23 19:07 UTC, Tschonti commented on apps/backend/src/events/events.service.ts
> +              : undefined,
you can revert these changes, for me it works with the old version

2024-09-23 19:07 UTC, Tschonti commented on apps/frontend/src/app/events/new/page.tsx
>      }
not sure what you're trying to do here, but nothing happens if you add a drink that is already in the drinkActions array.
but the whole ordeal with the drinkactions can be handled in a future PR

2024-09-23 19:07 UTC, Tschonti commented on apps/frontend/src/app/events/new/page.tsx
> +async function onSubmit(values: z.infer<typeof formSchema>) {
we should call `event.preventDefault()` at the begining of this function, so the standard HTML form is not submitted (you can see the URL change when you click save). Not sure how to get access to the event object in this function tho

2024-09-23 19:07 UTC, Tschonti commented on package-lock.json
please delete this file and remember to install packages with yarn

2024-09-23 19:34 UTC, murtagh27 commented on apps/frontend/src/app/events/new/page.tsx
>      }
oh it used to work, i must have messed it up.. but okay i will handle it in a future pr

2024-09-23 21:05 UTC, Tschonti commented
just remove the console logs and vercel will be happy as well

2024-09-24 09:25 UTC, Tschonti approved these changes

2024-09-24 10:23 UTC, merged